export default {
  sureToDeleteChat: "Are you sure to delete this chat?",
  longPressToSee: "Hold to view",

  interactionRequestNotif: "Interaction Request",
  giftNotif: "Gift/Coin",
  areYouSureToAddItem: "Are you sure you want add this babl to collection?",
  itemAddedToCollection: "Babl added to collection.",
  goOrigin: "Are you sure you want to go with the original content?",
  follower: "Follower",
  following: "Following",
  languageSelection: "Language selection",
  continue: "Continue",
  OnBoardDescOne:
    " We show you the most relevant content and offers while shopping. Browse through categories and easily find the products you want. We're here to choose the best for you!Pazaarfy is here to make your shopping experience more fun and easy. You can sell your own products or take advantage of the amazing deals offered by others. Start exploring now!",
  Skip: "Skip",
  Send: "Send",
  SendYourComplaint: "Send Your Complaint",
  SendBablCoin: "Send Babl Coin",
  OnBoardDescTwo:
    "Send content to Babl from another platform and find it later in the Share Library.",
  OnBoardThree:
    "Enjoy shopping at Pazaarfy with the latest deals and discounts. Step into a world full of promotions and start saving now!",
  OnBoardFour:
    "When creating Babl, select content from affiliated platforms, choose an attractive template, and it is recommended to choose a dynamic cover.",
  OnBoardFive:
    "Using the Sub Babl function, you can create subheadings under any topic and examine the topic in more depth.",
  OnBoardSix:
    "You can add content in a permitted format under a subheading on a topic you are interested in and encourage interaction.",
  TotalAssets: "Total Assets",
  Continue: "Continue",
  Login: "Login",
  Email: "Email",
  Password: "Password",
  Forgot: "Did you forget?",
  LoginGmail: "Sign in with Google",
  LoginApple: "Sign in with Apple",
  DontHaveAnAccount: "Don't have an account yet?",
  DoHaveAnAccount: "Already have an account?",
  SignUp: "Register",
  Username: "Username",
  PasswordAgain: "Password Repeat",
  WhatDoYouLike: "What do you like?",
  SelectYourInterests: "Select your interests",
  Which: "Which",
  MyBabls: "My Babls",
  DoYouLikeTheContentStyle: "What kind of content do you like?",
  ShortVideo: "Short Video",
  SelectBablFromHere: "Select babl from here.",
  TapToGoToSiteForShareContentToSharedSavings:
    "Tap to go to site for share content to Share Library",
  Video: "Video",
  Photo: "Photograph",
  Text: "Text",
  Music: "Music/Podcast",
  LiveStream: "Live broadcast",
  Shop: "Shopping",
  Internet: "Internet",
  ForYou: "For you",
  Following: "Following",
  FollowedBabls: "Followed Babls",
  Collections: "My Collections",
  NewCollections: "New collection",
  EnterCollectionName: "Enter Collection Name",
  Cancel: "Cancel",
  Save: "Save",
  MakeItPublic: "Make it public",
  CollectionsDesc:
    "Collections set as public appear on your profile and can be shared with friends.",
  whatKindOfTopicYouThinking: "What kind of topic are you thinking of?",
  title: "Title",
  enterBablTitle: "Enter product description",
  all: "All",
  spor: "Sport",
  health: "Health",
  economy: "Economy",
  beauty: "Beauty",
  shopping: "Shopping / E-Commerce",
  technology: "Technology",
  other: "Other",
  createAutoBabl: "Create Automatic Babl",
  enterDetailedPrompt: "Enter Detailed Prompt",
  createBabl: "Add Product",
  selectedCategory: "Selected Category",
  video: "Video",
  shortVideo: "Short Video",
  photo: "Photo",
  text: "Text",
  music: "Music/Podcast",
  stream: "Stream",
  shop: "Shop",
  internet: "Internet",
  ai: "AI",
  createYourself: "Create",
  pleaseSelectAtLeastContent: "Please add at least 1 piece of content",
  search: "Search..",
  Search: "Search",
  BablSearch: "Babl search",
  templateSelection: "Template",
  WithDraw: "Withdraw",
  edit: "Edit",
  finish: "Finish",
  add: "Add",
  createNewBabl: "Create Sub Babl",
  addExistingBabl: "Add Existing Babl",
  changeTemplate: "Change Template",
  regenerate: "Regenerate",
  enterHashtag: "#Enter hashtag",
  videoAndShortVideo: "From the video",
  share: "Share",
  selectCover: "Select Cover",
  interaction: "Interaction",
  allowOthersToAdd: "Allow others to add this babl to any babl they want",
  save: "Kaydet",
  bablSettings: "Babl Settings",
  enterInfo: "Info Ekleyin",
  profileSettings: "Profile Settings",
  exit: "Log out",
  controlPanel: "Control Panel",
  account: "Account",
  saved: "Saved",
  Savedd: "Saved",
  AddCollections: "Add Collections",
  GoToProfile: "Go To Profile",
  NotInterested: "Not Interested",
  paymentTransactions: "Payment Transactions",
  notifications: "Notifications",
  help: "Help",
  about: "About",
  sureToLogout: "Are you sure you want to log out?",
  cancel: "Cancel",
  yes: "Yes",
  no: "No",
  requestsIGet: "Requests I Get",
  requestsISent: "Requests I Sent",
  userDetails: "User Details",
  password: "Password",
  verification: "Verification",
  language: "Language",
  deleteMyAccount: "Delete my Account",
  changePasswordDesc: "Enter your email address to change your password",
  sureToDeleteAccount: "Are You Sure You Want to Delete the Account?",
  myAccount: "Account",
  profileView: "Profile View",
  dontHaveEnoughCoins: "You do not have enough coins.",
  wouldYouLikeToBuyCoins: "Would you like to buy coins?",
  errorOccuredUnlockingBabl:
    "An error occurred while unlocking babl. Please try again later.",
  areYouSure: "Are you sure?",
  areYouSureToAcceptInteraction:
    "Are you sure you want to accept adding the content to your Babl?",
  areYouSureToDenyInteraction:
    "Are you sure you want to deny adding the content to your Babl?",
  youAreDeletingBabl: "You are deleting post.",
  requestSent: "Request sent.",
  requestAccepted: "Request accepted.",
  requestDenied: "Request denied.",
  pleaseEnterValidPrice: "Please enter a valid price",
  pleaseSelectIntro: "Please select intro",
  noGalleryAccess: "Access to the gallery was not granted.",
  wouldYouLikeToGoSettins: "Would you like to go to settings and grant access?",
  selectCoverFirst: "Please select cover first",
  pleaseEnterBablTitle: "Please enter product description",
  pleaseSelectBablCategory: "Please select Babl Category",
  pleaseEnterPrompt:
    "Please enter the prompt or turn off the automatic babl creation option.",
  pleaseWaitUntilAutomaticBablFinish:
    "Automatic babl is being created, please wait until it is created.",
  automaticBablGenerated: "Automatic babl created",
  pleaseSelectTemplate: "Please select template",
  congratsSubBablAdded: "Congratulations, sub-section added",
  congratsBablShared: "Congratulations, post shared",
  bablPriceCantNegative: "Babl price cannot be negative.",
  areYouSureToCancelBabl: "Are you sure you want to cancel product?",
  SelectVideoOrPhotoToAddProduct: "Select video or photo to add product",
  ReanimatedSharedValue: "Reanimated Shared Value",
  Saved: "Saved",
  ShareLibrary: "Share Library",
  AutomaticBablCreation: "Automatic Babl Creation",
  Loading: "Loading %",
  PrivacyPolicy: "Privacy Policy",
  Followss: "Follows",
  TermsOfUse: "Terms of Use",
  About: "About",
  AppNotifications: "In - app Notifications",
  Likes: "Likes",
  Rebabls: "Rebabls",
  Sends: "Sends",
  Comments: "Comments",
  Followers: "Followers",
  FollowersL: "Followers",
  Messages: "Messages",
  Live: "Live",
  NewPost: "New Post",
  ThereIsARegisteredEaddress:
    "There is a registered user with this username or e-mail address.",
  YourPasswordHasBeenReset: "Your password has been reset",
  VerificationCodeNotFound: "Verification code not found",
  VerificationCodeIsIncorrect: "Verification code is incorrect",
  AnErrorPassword: "An error occurred while resetting the password.",
  EnterYourNewPassword: "Enter your new password",
  VerificationCode: "Verification Code",
  YourNewPassword: "Your new password",
  YourNewPasswordAgain: "Your new password again",
  PasswordRepeat: "Password does not match its repeat.",
  CreateMyNewPassword: "Create My New Password",
  GetCode: "Get Code",
  AnErrorOccurredWhileSendingTheVerificationCode:
    "An error occurred while sending the verification code.",
  SendVerificationCode: "Send Verification Code",
  CanAddress: "Can you write your email address",
  CONGRATULATIONS: "CONGRATULATIONS!",
  YourNewPasswordSuccessfully:
    "Your new password has been created successfully.",
  ThereIsAddress:
    "There is a registered user with this username or e-mail address.",
  YourPasswordLong: "Your password must be at least 8 characters long",
  AnUnexpectedErrorOccurred: "An unexpected error occurred.",
  AnErrorLogging: "An error occurred while logging in.",
  ItMustBeTheSameRepeat: "It must be the same as your password repeat.",
  Sport: "Sport",
  Health: "Health",
  Economy: "Accessory",
  Beauty: "Beauty",
  Shopping: "Shopping",
  Technology: "Technology",
  Trip: "Trip",
  Politics: "Politics",
  FoodDrink: "Food and Drink",
  Entertainment: "Entertainment",
  Current: "Current",
  Magazine: "Magazine",
  Activities: "Activities",
  Fashion: "Fashion",
  Culture: "Culture",
  Education: "Education",
  Art: "Art",
  Design: "Design",
  Nature: "Nature",
  Work: "Work",
  Motivation: "Motivation",
  SelfImprovement: "Self-improvement",
  Psychology: "Psychology",
  Science: "Science",
  Universe: "Universe",
  ThisOwner: "This babl is locked by its owner.",
  WantToUnlockCoinsWrong: "WantToUnlockCoinsWrong?",
  AreYouBabl: "Are you sure you want to unlock Babl?",
  BablSaved: "Post saved.",
  BookmarkHasBeenDeleted: "Bookmark has been deleted.",
  UserBlocked: "User blocked.",
  BablHasBeenDeleted: "Post has been deleted.",
  MarkedAsNotInterested: "Marked as not interested.",
  Report: "Report",
  Hide: "Objectionable Content",
  BlockUser: "Block User",
  AreYouUser: "Are you sure to block this user?",
  GetOutRebabs: "Get out of my rebabs",
  Delete: "Delete",
  Edit: "Edit",
  rebabledby: "rebabled by",
  BablCategories: "Categories",
  Rebabled: "Rebabled",
  PleaseSelectContent: "Please select at least 1 piece of content",
  YouWillSendARequestToAddContentAreYouSure:
    "You will send a request to add content. Are you sure?",
  Follow: "Follow",
  Followingg: "Following",
  all: "Electronic",
  SexualContent: "Sexual Content",
  ViolentOrRepulsiveContent: "Violent or repulsive content",
  HatefulOrAbusiveContent: "Hateful or abusive content",
  HarassmentOrBullying: "Harassment or bullying",
  HarmfulOrDangerousActs: "Harmful or dangerous acts",
  Misinformation: "Misinformation",
  ChildAbuse: "Child abuse",
  LegalIssue: "Legal issue",
  PromotesTerrorism: "Promotes terrorism",
  SpamOrMisleading: "Spam or misleading",
  Other: "Other",
  YourReportSent: "Your report has been sent",
  PleaseSelectOption: "Please select an option",
  CollectionDeleted: "Collection deleted",
  Public: "Public",
  Private: "Private",
  AreYouSureCollection: "Are you sure you want to delete the collection?",
  PleaseEnterYourMessage: "Please enter your message",
  AIGENERATEDTEXT: "AI GENERATED TEXT",
  BablFollowers: "Babl Followers",
  ManageBabls: "Manage Babls",
  Shared: "Shared",
  CongratulationsSsuccessfully:
    "Congratulations, it has been added successfully.",
  AddToShareLibrary: "Add to Share Library",
  CongratulationsItHasBeenAddedSuccessfully:
    "Congratulations It Has Been Added Successfully",
  OK: "Okey",
  Answers: "Answers",
  AddComment: "Add comment..",
  wouldYouLikeToDeleteYourComment: "Would you like to delete your comment?",
  YourCommentHasBeenDeleted: "Your comment has been deleted.",
  AreYouSureToDelete: "Are you sure to delete?",
  PleaseCheckYourInternetConnection: "Please Check Your Internet Connection",
  close: "Close",
  CollectionBabls: "Collection Babls",
  AddedTo: "Şuraya eklendi",
  SelectTextFromHere: "Select Text From Here",
  SelectFromHere: "Select from here.",
  SelectStreamFromHere: "Select stream from here.",
  SelectShortFromHere: "Select short from here.",
  SelectProductFromHere: "Select product from here.",
  SelectMusic: "Select music from",
  SelectVideoFromHere: "Select video from here",
  TapScreenToEnter: "Tap Screen to Enter",
  WouldYouLikeToGoOriginalContent: "Would you like to go original content?",
  Daily: "Daily",
  Weekly: "Weekly",
  Monthly: "Monthly",
  HotBabls: "Hot Babls",
  ShareTo: "Share to",
  CopyLink: "Copy Link",
  BablSent: "Babl sent!",
  WriteAMessage: "Write a message..",
  BablLinkCopied: "Babl link copied",
  AnErrorOccurredLater:
    "An error occurred while deleting data, please try again later.",
  Transactions: "Transactions",
  Deposit: "Deposit",
  Withdraw: "Withdraw",
  Gifts: "Gifts",
  MyGifts: "My Gifts",
  SearchTransaction: "Search Transaction",
  Payment: "Payment",
  Congratulations: "Congratulations",
  Verification: "Verification",
  ConfirmTheCodeReceivedInYourEmail: "Confirm the Code Received in Your Email",
  Confirm: "Confirm",
  DeleteCollection: "Delete Collection",
  AreYouSureYouWantToDeleteTheCollection:
    "Are you sure you want to delete the collection?",
  Sorry: "Sorry :(",
  YourAccountHasBeenSuccessfullyDeleted:
    "Your account has been successfully deleted",
  CreateNewAccount: "Create New Account",
  AreYouSureToBlockUser: "Are you sure to block user?",
  AnErrorOccured: "An error occured.",
  AreYouSureToReportUser: "Are you sure to report user?",
  ReportUser: "Engelle",
  Success: "Success",
  WouldYouLikeToRemovePin: "Would you like to remove pin?",
  WouldYouLikeToPinThisBabl: "Would you like to pin this babl?",
  ManageContentsBabls: "Manage contents to be added to your Babls.",
  ManageYourAccountUpdateYourprofileInformationAndConfigureYourPreferences:
    "Manage your account, update your profile information, and configure your preferences.",
  BalanceAndMonetary: "Balance and Monetary",
  CheckYourTransactions:
    "Check your balance, view your payment history, and manage your financial transactions.",
  AdjustImportantEvents:
    "Adjust your notification preferences, receive updates, and stay informed about important events.",
  LearnDevelopers:
    "Learn more about the app, check the version number, and contact developers.",
  VerificationSystem: "Verification System",
  Contents: "Contents",
  People: "People",
  Hashtag: "Hashtag",
  CreBabl: "Create Babl..",
  YouDontYet: "You dont have any content you follow yet.",
  Yesterday: "Yesterday",
  Today: "Today",
  Notifications: "Notifications",
  ProfileInformationUpdated: "Profile Information Updated",
  ProfileSettings: "Profile Settings",
  AccessPermissionGranted: "Access permission to the gallery was not granted.",
  DoYouWantAccess: "Do you want to go to settings and grant access?",
  PersonalInformation: "Personal Information",
  name: "Store Name",
  SocialMediaLink: "Social Media Links",
  BablFocusedNoSlide: "Babl focused (no slider)",

  BackgroundFocusedWithSlider: "Background focused (with slider)",
  ModernDesign: "Modern Design",
  EasyToConsume: "Easy to Consume",
  AmountOfMoney: "Amount of Money",
  Convert: "Convert",
  ConvertibleGift: "Convertible Gift",
  Amount: "Amount",
  ConvertibleCoin: "Convertible Coin",
  ConvertToBablCoin: "Convert to Babl Coin",
  Pull: "Pull",
  YouDoNotHaveEnoughFunds: "You do not have enough funds.",
  PleaseCorrectly: "Please make sure you entered your Iban number correctly.",
  ThereIsNoGiftInYourAccount: "There is no gift in your account.",
  YouBuy:
    "You do not have enough coins in your account. Would you like to buy?",
  YourCreated: "Your withdrawal request has been created.",
  WithdrawalProcess: "Withdrawal Process",
  ThisMonth: "This Month",
  Tulip: "Tulip",
  GoldBall: "Gold Ball",
  Coconut: "Coconut",
  Coffee: "Coffee",
  Heart: "Heart",
  JavaCoffee: "Java Coffee",
  Cat: "Cat",
  Dog: "Dog",
  SoyBeans: "Soy Beans",
  Badge: "Badge",
  Peanut: "Peanut",
  Lipstick: "Lipstick",
  TraditionalGong: "Raditional Gong",
  Bison: "Bison",
  Mask: "Mask",
  WayangSymbols: "Wayang Symbols",
  Wand: "Wand",
  BakpiaPathong: "Bakpia Pathong",
  JamGodang: "Jam Godang",
  Wayang: "Wayang",
  GameConsol: "Game Consol",
  DeepSearch: "Deep Search",
  OliveBranch: "Olive Branch",
  GoldPen: "GoldPen",
  RambutanFruit: "Rambutan Fruit",
  GoldMedal: "Gold Medal",
  Flower: "Flower",
  TraditionalWoodcraft: "Traditional Woodcraft",
  GoldenCup: "Golden Cup",
  Astreoid: "Astreoid",
  MagicSphere: "Magic Sphere",
  Ring: "Ring",
  Diamond: "Diamond",
  MentalHealth: "Mental Health",
  PersonalGrowth: "Personal Growth",
  NatureBios: "Nature/Bios",
  CultureEducation: "Culture / Education",
  CreativeArtDesign: "Creative / Art / Design",
  MusicLiteratureCinema: "Music / Literature / Cinema",
  MagazineEvents: "Magazine / Events",
  WorldNews: "World News",
  FoodaDrink: "Food & Drink",
  TravelExplore: "Travel / Explore",
  PoweredByAI: "Powered by AI",
  Done: "Done",
  Recharge: "Recharge",
  CongratulationsAccount:
    "Congratulations, the coin has been added to your account.",
  AnUnexpectedLater:
    "An unexpected error occurred during purchase. Please try again later.",
  BuyCoins: "Buy Coins",
  Filter: "Filter",
  Bookmarks: "Bookmarks",
  AddHeaderWithinBabl: "Add Header Within Babl",
  AddBackground: "Add Background",
  Info: "Info",
  ChooseShortTopic: "Choose a short video cover for your topic",
  YouCanTopic: "You can write anything about your topic",
  Price: "Price",
  AddYourText: "Add your text...",
  NewMessage: "New Message",
  howtoday: "how can I assist you today?",
  BABLAI: "BABLAI",
  AskAnything: "Ask anything",
  ThisByUser: "This babl was deleted by the user",
  UpdateMyNewPassword: "Update My New Password",
  ConfirmEmail: "Confirm the Code Received in Your Email",
  ErrorGift:
    "An unexpected error occurred while sending a gift. Please try again later.",
  YouAreBuying: "You are buying",
  YouAreSending: "You are sending",
  AreYourSure: "Are you sure?",
  Saveddd: "Saved",
  Gift: "Gift",
  Buy: "Buy",
  CongratulationsCoinSent: "Congratulations, coin sent.",
  YouCantYourself: "You can't send coin to yourself.",
  PleaseEnterTheSend: "Please enter the amount you want to send",
  YouCanSendBablCongrats: "You can send babl coin or gifts to congrats",
  EnterCustomAmount: "Enter custom amount",
  YouYet: "You dont have any shared content yet.",
  AreYouDelete: "Are you sure to delete?",
  YouCanSendGift: "You can send Gift",

  Temp1Desc:
    "You can focus on Babls, no space between and there is no slider function for grouping.",
  BablFocusedSlider: "Babl focused (with slider)",
  Temp2Desc:
    "You can focus on Babls, no space between and there is slider function for grouping.",
  BackgroundFocusedNoSlider: "Background focused (no slider)",
  Temp3Desc:
    "You can have a background on your Babls, more space between and there is no slider function for grouping.",
  Temp4Desc:
    "You can have a background on your Babls, more space between and there is slider function for grouping.",
  Temp5Desc:
    "Placements of Babls have no spesific rules, contains a little bit design and slider function is optinal.",
  Temp6Desc:
    "You can display a large amount of content in an organized manner and slider function is optinal.",
  helpandfeedback: "Help And Feedback",
  helpdc: "Access help and support resources and resolve issues.",
  feedback: "Feedback",
  pleasefeedback: "Please add your feedback",
  feedbackSent: "Feedback sent.",
  fq1: "What types of content can be found on Bablworld?",
  fqd1: "Bablworld offers a wide range of formats including text, images, videos, short videos, live broadcasts, products, music, podcasts, all kinds of web pages, pdf and other media types. Users can combine different formats to best convey their topics.",
  fq2: "How is artificial intelligence used in practice?",
  fqd2: "Artificial intelligence in the application works to analyze user behavior, provide personalized recommendations, optimize content according to the user and improve the application experience. When creating Babl, users can select and edit the best and most accurate content by taking advantage of artificial intelligence integration. This helps users create more effective and engaging Babls.",
  fq3: "How Can I Solve Login Problems?",
  fqd3: 'You can create a new password using the "Forgot My Password" option or contact the application support team.',
  fq4: "How Does the App Use My Data?",
  fqd4: "To protect your privacy, your personal data is used only for application functionality and is not shared with third parties. Data is encrypted and stored on secure servers.",
  fq5: "What should I do to get the most accurate results in automatic connection?",
  fqd5: "The more detailed, specific and diverse information is written in the information section during the automatic Babl creation phase, the more accurate the result will be. The user must give the clearest commands and keywords to the artificial intelligence to create the Babl in his mind.",
  popup: "Continue",
  PhoneNumber: "Phone Number",
  SignUpComplete: "Sign Up Complete",
  settings: "Settings",
  PazaarfyPremium: "Pazaarfy Premium",
  ProfileInformation: "Profile Information",
  ChangeLanguage: "Change Language",
  LiveSupport: "Live Support",
  PrivacyAgreement: "Privacy Agreement",
  changePassword: "Change Password",
  ChangePassword: "Change Password",
  editInformation: "Edit information",
  selectCategory: "Select Category",
  MyStore: "My Store",
  AddProduct: "Add Product",
  Close: "Close",
  writemessage: "Write a message",
  Pazar: "Market",
  SearchProduct: "Search for products",
  Product: "Product",
  PazaarfyAI: "Artificial Intelligence",
  NoMatchingProductFound: "No matching product found",
  PleaseSelectPhotoOrVideo: "Please select a video or image",
  Logout: "Logout",
  Sends: "Posts",
  Likeda: "Favorites",
  Trend: "Trending Products",
  BestSellers: "Best Sellers",
  Notifications: "Notifications",
  reply: "reply",
  SelectFromGallery: "Select From Gallery",
  OpenCamera: "Open Camera",
  ForgotPasswordF: "Forgot My Password",
  UsernameReq: "Username is required",
  EmailReq: "Email is required",
  il1: "🛍️ Fashion & Accessories",
  id1: "Clothing, shoes, bags, and jewelry",
  il2: "📱 Technology & Electronics",
  id2: "Smartphones, computers, headphones",
  il3: "🏠 Home & Living",
  id3: "Decoration, kitchenware, furniture",
  il4: "💄 Cosmetics & Personal Care",
  id4: "Makeup, skincare, perfumes",
  il5: "🎮 Gaming & Entertainment",
  id5: "Consoles, board games, figurines",
  il6: "🏋️‍♀️ Sports & Outdoor",
  id6: "Fitness equipment, camping gear",
  sl1: "🔥 Trend & Popular Products",
  sl2: "🎥 Video-Based Content",
  sl3: "📸 Highly Visual",
  sl4: "⏳ Short & Concise Information",
  sl5: "🛒 Discount & Campaign Focused",
  sl6: "🌍 Global & Innovative Products",
  MySituation: "My Status",
  SearchUser: "Search for User",
  Warnings: "Warning",
  PhotoWarning: "Please select at least one photo",
  PhotoFive: "You can upload up to 5 contents",
  TermsText: "I have read and accept the Terms of Use.",
  errorKVKK: "You must accept the terms of use.",
  Back: "Back",
  PreHome: "Featured Products",
  Stores: "Stores",
  HideDescription:
    "Your Offensive Content Notification Has Been Received Your notification has been successfully received. Our content team will perform the necessary checks and will remove the content within 24 hours or send a written warning to the relevant user. Thank you for your interest and support.",
  GetNotification: "Notification Received",
  GuestMode: "Guest Mode",
  LeaveGuestMode: "Leave Guest Mode",
  kv1: "Pazaarfy Terms of Use",
  kv2: "These terms outline the rules that must be followed while using the Pazaarfy app. Pazaarfy aims to create a safe, respectful, and positive environment among its users. Therefore, the following behaviors are strictly prohibited: sharing content that is illegal, violent, obscene, hateful, or harassing; threatening, insulting, bullying, or engaging in any kind of disturbing behavior towards other users; and any actions that harm the functionality of the app, such as spam, fraud, or abuse. Accounts that violate these rules will be terminated within 24 hours.",
  kv3: "1. Service Description",
  kv4: "Pazaarfy is a social marketplace app where users can view, list, and share products.",
  kv5: "2. Acceptable Use",
  kv6: "Users may not share content that is illegal, offensive, threatening, hateful, or obscene.",
  kv7: "3. Content Moderation",
  kv8: "Inappropriate content can be reported by users and will be reviewed by moderators within 24 hours.",
  kv9: "4. Blocking and Reporting",
  kv10: "Users can block other users and report inappropriate content.",
  kv11: "5. Privacy",
  kv12: "Shared content may be publicly visible. It is your responsibility to protect your private information.",
  kv13: "6. Breach of Agreement",
  kv14: "Accounts violating the rules may be suspended or terminated without warning.",
  preview: "PREVİEW",
  InfoMarket: "Store Information",
  ShareProfile: "Share Profile",
  ShareLink: "Find your store on the Pazaarfy app",
  LikedStore: "Stores You May Like",
  SearchStore: "Search Store",
  ShareStatus: "Share as Status",
  GenerateQR: "Generate QR",
};
