export default {
  sureToDeleteChat: "Bu konuşmayı silmek istediğine emin misin?",
  longPressToSee: "Görüntülemek için basılı tut",

  interactionRequestNotif: "Interaction Request",
  giftNotif: "Gift/Coin",
  areYouSureToAddItem:
    "Bu gönderiyi koleksiyona eklemek istediğine emin misin?",
  itemAddedToCollection: "Gönderi koleksiyona eklendi.",
  goOrigin: "Orijinal içeriği gitmek istedinize emin misin?",
  follower: "Takipçi",
  following: "Takip",
  languageSelection: "Dil Değiştir",
  continue: "Devam",
  selectedCategory: "Kategori Seçin",

  OnBoardDescOne:
    "Pazaarfy, alışveriş deneyiminizi daha eğlenceli ve kolay hale getirmek için burada. Kendi ürünlerinizi satabilir, başkalarının sunduğu harika fırsatlardan yararlanabilirsiniz. Şimdi keşfetmeye başlayın!",
  Skip: "Geç",
  OnBoardDescTwo:
    "Alışveriş yaparken size en uygun içerikleri ve fırsatları gösteriyoruz. Kategorilere göz atın ve istediğiniz ürünleri kolayca bulun. Sizin için en iyisini seçmek için buradayız!",
  OnBoardThree:
    "Her zaman güncel fırsatlar ve indirimlerle Pazaarfy'de alışveriş yapmanın keyfini çıkarın. Kampanyalarla dolu bir dünyaya adım atın ve şimdi tasarruf edin!",
  OnBoardFour:
    "Babl oluştururken bağlı platformlardan içerik seçin, ilgi çekici bir şablon seçin ve dinamik bir kapak seçmeniz önerilir.",
  OnBoardFive:
    "Alt Babl fonksiyonunu kullanarak herhangi bir konu başlığı altında alt başlıklar oluşturabilir ve konuyu daha derinlemesine inceleyebilirsiniz.",
  OnBoardSix:
    "İlgilendiğiniz bir konuda alt başlık altına izin verilen formatta içerik ekleyebilir ve etkileşimi teşvik edebilirsiniz.",
  Continue: "Devam",
  Login: "Giriş Yap",
  Email: "Eposta",
  Search: "Ara",
  MyBabls: "Babllarım",
  share: "Paylaş",
  SelectBablFromHere: "Buradan bablı seçin.",
  TapToGoToSiteForShareContentToSharedSavings:
    "Paylaşım Kütüphanesinde içerik paylaşmak üzere siteye gitmek için dokunun",
  BablSearch: "Babl Arama",
  Password: "Şifre",
  Forgot: "Unuttun mu?",
  LoginGmail: "Google ile Giriş Yap",
  LoginApple: "Apple ile Giriş Yap",
  account: "Hesap",
  DontHaveAnAccount: "Henüz bir hesabın yok mu?",
  DoHaveAnAccount: "Zaten bir hesabın var mı?",
  SignUp: "Kayıt Ol",
  Username: "Kullanıcı adı",
  PasswordAgain: "Şifre Tekrar",

  WhatDoYouLike:
    "Özelleştirilmiş iş çözümleri için ana alım amacınızı bize bildirin",
  SelectYourInterests: "İlgi alanları seçiniz",
  createYourself: "Oluştur",
  Which: "Hangi",
  DoYouLikeTheContentStyle: "İçerik tarzını seversiniz?",
  ShortVideo: "Kısa Video",
  Video: "Video Tanıtımlı Ürünler ",
  Photo: "Galeriden",
  Text: "Yazı",
  Music: "Müzik/Podcast",
  LiveStream: "Canlı Yayın",
  Followss: "Takipler",
  Shop: "Alışveriş",
  Internet: "Internet",
  ForYou: "Sana Özel",
  Following: "Takip",
  FollowedBabls: "Takip Edilen Babllar",
  Collections: "Koleksiyonlarım",
  NewCollections: "Yeni Koleksiyon",
  EnterCollectionName: "Koleksiyon İsmi Gir",
  Cancel: "Vazgeç",
  cancel: "Vazgeç",
  Save: "Kaydet",
  MakeItPublic: "Herkese açık yap",
  CollectionsDesc:
    "Herkese açık olarak ayarlanan koleksiyonlar profilinizde gösterilir ve arkadaşlarla paylaşılabilir.",
  whatKindOfTopicYouThinking: "Nasıl bir konu düşünüyorsun?",
  ReanimatedSharedValue: "Yeniden Canlandırılmış Paylaşılan Değer",
  Saved: "Kaydet",
  Saveddd: "Kaydedilenler",
  Savedd: "Kaydedildi",
  ShareLibrary: "Kütüphane",
  AutomaticBablCreation: "Otomatik Babl oluşturuluyor",
  Loading: "Yükleniyor %",
  PrivacyPolicy: "Gizlilik Politikası",
  notifications: "Bildirimler",
  TermsOfUse: "Kullanım Kılavuzu",
  About: "Hakkında",
  AppNotifications: "Bildirim Ayarları",
  Likes: "Beğeniler",
  Rebabls: "Rebabls",
  Sends: "Gönderiler",
  Comments: "Yorumlar",
  changePasswordDesc: "Şifrenizi değiştirmek için eposta adresinizi girin",
  Followers: "Takipçi",
  FollowersL: "Takipçiler",
  Messages: "Mesajlar",
  Live: "Anlık",
  NewPost: "Yeni Gönderi",
  ThereIsARegisteredEaddress:
    "Bu kullanıcı adı veya e-posta adresiyle kayıtlı bir kullanıcı var.",
  YourPasswordHasBeenReset: "Şifreniz sıfırlandı",
  VerificationCodeNotFound: "Doğrulama kodu bulanamadı",
  VerificationCodeIsIncorrect: "Doğrulama kodu hatalı",
  AnErrorPassword: "Şifre sıfırlanırken bir hata oluştu..",
  EnterYourNewPassword: "Yeni şifrenizi girin",
  VerificationCode: "Doğrulama Kodu",
  YourNewPassword: "Yeni Şifren",
  YourNewPasswordAgain: "Yeni Şifren Tekrar",
  PasswordRepeat: "Şifre tekrarıyla eşleşmiyor.",
  CreateMyNewPassword: "Yeni Şifremi Oluştur",
  GetCode: "Kod Gönder",
  AnErrorOccurredWhileSendingTheVerificationCode:
    "Doğrulama kodu gönderilirken bir hata oluştu.",
  SendVerificationCode: "Doğrulama Kodunu Gönder",
  CanAddress: "Email adresinizi yazar mısınız",
  CONGRATULATIONS: "TEBRİKLER!",
  YourNewPasswordSuccessfully: "Yeni şifreniz başarıyla oluşturuldu.",
  ThereIsAddress:
    "Bu kullanıcı adı veya e-posta adresiyle kayıtlı bir kullanıcı var.",
  YourPasswordLong: "Şifreniz en az 8 karakter uzunluğunda olmalıdır.",
  AnUnexpectedErrorOccurred: "Beklenmedik bir hata oluştu.",
  AnErrorLogging: "Giriş yaparken bir hata oluştu.",
  ItMustBeTheSameRepeat: "Şifre tekrarınızla aynı olmalıdır.",
  Sport: "Spor",
  Health: "Sağlık",
  Economy: "Aksesuar",
  Beauty: "Güzellik",
  Shopping: "Alışveriş",
  Technology: "Teknoloji",
  Trip: "Seyahat",
  Politics: "Politika",
  FoodDrink: "Yeme ve İçme",
  Entertainment: "Eğlence",
  Current: "Akım",
  Magazine: "Magazin",
  Activities: "Aktivite",
  Fashion: "Moda",
  Culture: "Kültür",
  Education: "Eğitim",
  Art: "Sanat",
  Design: "Tasarım",
  Nature: "Doğa",
  Work: "Çalışma",
  Motivation: "Motivasyon",
  SelfImprovement: "Kişisel gelişim",
  Psychology: "Psikoloji",
  Science: "Bilim",
  Universe: "Evren",
  ThisOwner: "Bu babl, sahibi tarafından kilitlendi.",
  WantToUnlockCoinsWrong: "coin karşılığında kilidi açmak ister misin?",
  Yes: "Evet",
  AreYouBabl: "Bablın kilidini açmak istediğinden emin misin?",
  BablSaved: "Gönderi kaydedildi",
  BookmarkHasBeenDeleted: "Yer işareti silindi.",
  UserBlocked: "Kullanıcı Bloklandı",
  BablHasBeenDeleted: "Gönderi silindi.",
  AddCollections: "Koleksiyona Ekle",
  GoToProfile: "Profile Git",
  NotInterested: "İlgilenmiyorum",
  MarkedAsNotInterested: "İlgilenmiyorum olarak işaretlendi.",
  Report: "Şikayet Et",
  Hide: "Sakıncalı İçerik",
  BlockUser: "Kullanıcıyı Blokla",
  AreYouUser: "Bu kullanıcıyı engellemek istediğinize emin misiniz?",
  areYouSure: "Emin misin?",
  areYouSureToAcceptInteraction:
    "İçeriği Babl`ınıza eklemeyi kabul etmek istediğinizden emin misiniz?",
  GetOutRebabs: "Rebabllarımdan Çıkar",
  Delete: "Sil",
  youAreDeletingBabl: "Gönderiyi siliyorsun.",
  requestSent: "İstek gönderildi.",
  requestAccepted: "İstek kabul edildi.",
  requestDenied: "İstek reddedildi.",
  Edit: "Düzenle",
  rebabledby: "tarafından rebabllandı",
  PleaseSelectContent: "Please select at least 1 piece of content",
  YouWillSendARequestToAddContentAreYouSure:
    "İçerik eklemek için bir istek göndereceksiniz. Emin misin?",
  Follow: "Takip Et",
  Followingg: "Takip Ediliyor",
  SexualContent: "Cinsel İçerik",
  ViolentOrRepulsiveContent: "Şiddet içeren veya itici içerik",
  HatefulOrAbusiveContent: "Nefret dolu veya taciz edici içerik",
  HarassmentOrBullying: "Taciz veya zorbalık",
  HarmfulOrDangerousActs: "Zararlı veya tehlikeli eylemler",
  Misinformation: "Yanlış bilgi",
  ChildAbuse: "Çocuk istismarı",
  LegalIssue: "Yasal sorun",
  PromotesTerrorism: "Terörü teşvik ediyor",
  SpamOrMisleading: "Spam veya yanıltıcı",
  Other: "Diğer",
  YourReportSent: "Raporunuz gönderildi",
  PleaseSelectOption: "Lütfen bir seçenek seçin",
  CollectionDeleted: "Koleksiyon silindi",
  Public: "Açık",
  Private: "Gizli",
  AreYouSureCollection: "Koleksiyonu silmek istediğinizden emin misiniz?",
  no: "Hayır",
  Send: "Gönder",
  SendYourComplaint: "Şikayetinizi Gönderin",
  PleaseEnterYourMessage: "Lütfen mesajınızı girin",
  AIGENERATEDTEXT: "AI İLE OLUŞTURULMUŞ METİN",
  BablFollowers: "Babl Takipçileri",
  ManageBabls: "Babl Yönetimi",
  Shared: "Paylaşıldı",
  CongratulationsSsuccessfully: "Tebrikler, başarılı bir şekilde eklendi.",
  AddToShareLibrary: "Share Library’e Ekle",
  CongratulationsItHasBeenAddedSuccessfully: "Tebrikler Başarıyla Eklendi",
  OK: "Tamam",
  Answers: "Yanıtlar",
  AddComment: "Bir yorum yapın..",
  wouldYouLikeToDeleteYourComment: "Yorumu silmek istediğinize emin misiniz?",
  YourCommentHasBeenDeleted: "Yorumunuz silindi.",
  PleaseCheckYourInternetConnection:
    "Lütfen İnternet Bağlantınızı Kontrol Edin",
  requestsIGet: "Aldığım İstekler",
  requestsISent: "Gönderdiğim İstekler",
  controlPanel: "Kontrol Paneli",
  close: "Kapat",
  Close: "Kapat",
  bablSettings: "Babl ayarları",
  CollectionBabls: "Koleksiyon Bablları",
  AddedTo: "Şuraya eklendi",
  SelectTextFromHere: "Buradan Metni Seçin",
  SelectFromHere: "Buradan seçin.",
  SelectStreamFromHere: "Buradan akışı seçin.",
  SelectShortFromHere: "Buradan kısa videoyu seçin",
  SelectProductFromHere: "Buradan ürün seçin",
  SelectMusic: "Müzik Seç",
  all: "Elektronik",
  SelectVideoFromHere: "Buradan video seç",
  noGalleryAccess: "Galeriye erişim izni verilmedi.",
  wouldYouLikeToGoSettins: "Ayarlara gidip erişim izni vermek ister misiniz?",
  TapScreenToEnter: "Diğer Görseller İçin Tıkla",
  Rebabled: "Rebabllandı",
  WouldYouLikeToGoOriginalContent: "Orijinal içeriğe gitmek ister misiniz?",
  Daily: "Günlük",
  Weekly: "Haftalık",
  Monthly: "Aylık",
  HotBabls: "Trend Babllar",
  ShareTo: "Paylaş",
  CopyLink: "Linki kopyala",
  BablSent: "Babl gönderildi",
  WriteAMessage: "Mesaj yaz..",
  BablLinkCopied: "Babl linki kopyalandı",
  AnErrorOccurredLater:
    "Veriler silinirken bir hata oluştu, lütfen daha sonra tekrar deneyin.",
  userDetails: "Kullanıcı Detayları",
  password: "Şifre",
  language: "Dil",
  deleteMyAccount: "Hesabımı sil",
  sureToDeleteAccount: "Hesabı Silmek İstediğinize Emin misiniz?",
  Transactions: "İşlemler",
  Deposit: "Yükle",
  Withdraw: "Çekmek",
  Gifts: "Hediyeler",
  MyGifts: "Hediyelerim",
  TotalAssets: "Toplam Varlıklar",
  SearchTransaction: "İşlem Arama",
  Payment: "Ödeme",
  Congratulations: "Tebrikler",
  Verification: "Doğrulama",
  ConfirmTheCodeReceivedInYourEmail: "Mailinize Gelen Kodu Onaylayın",
  Confirm: "Onayla",
  DeleteCollection: "Koleksiyon silindi",
  AreYouSureYouWantToDeleteTheCollection:
    "Koleksiyonu silmek istediğinize emin misiniz?",
  Sorry: "Üzgünüz :(",
  YourAccountHasBeenSuccessfullyDeleted: "Hesabınız başarıyla silindi",
  CreateNewAccount: "Yeni Hesap Oluştur",
  AreYouSureToBlockUser: "Kullanıcıyı engellediğinizden emin misiniz?",
  AnErrorOccured: "Bir hata oluştu.",
  AreYouSureToReportUser: "Kullanıcıyı bildireceğinizden emin misiniz?",
  ReportUser: "Kullanıcıyı Raporla",
  Success: "Başarılı",
  WouldYouLikeToRemovePin: "Pini kaldırmak ister misiniz?",
  WouldYouLikeToPinThisBabl: "Bu babl`ı sabitlemek ister misiniz?",
  ManageContentsBabls: "Babl`ınıza eklenecek içerikleri yönetin.",
  ManageYourAccountUpdateYourprofileInformationAndConfigureYourPreferences:
    "Hesabınızı yönetin, profil bilgilerinizi güncelleyin ve tercihlerinizi yapılandırın.",
  BalanceAndMonetary: "Bakiye ve Parasal",
  CheckYourTransactions:
    "Bakiye durumunuzu kontrol edin, ödeme geçmişinizi görüntüleyin ve finansal işlemlerinizi yönetin.",
  AdjustImportantEvents:
    "Bildirim tercihlerinizi ayarlayın, güncellemeleri alın ve önemli etkinliklerden haberdar olun.",
  about: "Hakkında",
  AreYouSureToDelete: "Silmek istediğine emin misin",
  LearnDevelopers:
    "Uygulama hakkında daha fazla bilgi edinin, sürüm numarasını kontrol edin ve geliştiricilerle iletişime geçin.",
  sureToLogout: "Oturumu kapatmak istediğinizden emin misiniz?",
  profileSettings: "Profil Bilgileriniz",
  exit: "Çıkış",
  VerificationSystem: "Doğrulama Sistemi",
  Contents: "İçindekiler",
  People: "Kullanıcılar",
  Hashtag: "Etiketler",
  CreBabl: "Babl oluştur..",
  YouDontYet: "Henüz takip ettiğiniz bir içeriğiniz yok.",
  Yesterday: "Dün",
  Today: "Bugün",
  Notifications: "Bildirimler",
  ProfileInformationUpdated: "Profil bilgileri güncellendi",
  ProfileSettings: "Profil Ayarları",
  AccessPermissionGranted: "Galeriye erişim izni verilmedi.",
  DoYouWantAccess: "Ayarlara gidip erişim izni vermek istiyor musunuz?",
  PersonalInformation: "Kişisel Bilgiler",
  name: "Adınız",
  SocialMediaLink: "Sosyal Medya Linkleri",
  BablFocusedNoSlide: "Babl odaklı (slider yok)",
  BablFocusedSlider: "Babl odaklı (slider ile)",
  BackgroundFocusedNoSlider: "Arka plan odaklı (slider yok)",
  BackgroundFocusedWithSlider: "Arka plana odaklı (slider ile)",
  ModernDesign: "Modern Tasarım",
  EasyToConsume: "Kullanımı Kolay",
  pleaseSelectTemplate: "Lütfen şablon seç",
  templateSelection: "Şablon",
  WithDraw: "Çek",
  AmountOfMoney: "Para Miktarı",
  Convert: "Çevir",
  ConvertibleGift: "Dönüştürülebilir Hediye",
  Amount: "Miktar",
  ConvertibleCoin: "Dönüştürülebilir Para",
  ConvertToBablCoin: "Babl Coin`e Çevir",
  Pull: "Çekim",
  YouDoNotHaveEnoughFunds: "Yeterli paranız yok.",
  PleaseCorrectly: "Lütfen Iban numaranızı doğru girdiğinizden emin olun.",
  ThereIsNoGiftInYourAccount: "Hesabınızda hediye yok",
  YouBuy: "Hesabınızda yeterli miktarda coin yok. Satın almak ister misiniz?",
  YourCreated: "Para çekme talebiniz oluşturuldu.",
  WithdrawalProcess: "Para Çekme İşlemi",
  ThisMonth: "Bu Ay",
  Tulip: "Lale",
  GoldBall: "Altın Top",
  Coconut: "Hindistan Cevizi",
  Coffee: "Kahve",
  Heart: "Kalp",
  JavaCoffee: "Java Kahvesi",
  Cat: "Kedi",
  Dog: "Köpek",
  SoyBeans: "Soya Fasulyesi",
  Badge: "Rozet",
  Peanut: "Fasulye",
  Lipstick: "Ruj",
  TraditionalGong: "Geleneksel Gong",
  Bison: "Bizon",
  Mask: "Maske",
  WayangSymbols: "Wayang Sembolleri",
  Wand: "Değnek",
  BakpiaPathong: "Bakpia Pathong",
  JamGodang: "Jam Godang",
  Wayang: "Wayang",
  GameConsol: "Oyun Konsolu",
  DeepSearch: "Derin Arama",
  OliveBranch: "Zeytin Dalı",
  GoldPen: "Altın Kalem",
  RambutanFruit: "Rambutan Meyvesi",
  GoldMedal: "Altın Madalya",
  Flower: "Çicek",
  TraditionalWoodcraft: "Geleneksel Ağaç İşleri",
  GoldenCup: "Altın Kupa",
  Astreoid: "Asteroit",
  MagicSphere: "Sihirli Küre",
  Ring: "Yüzük",
  Diamond: "Elmas",
  MentalHealth: "Mental Sağlık",
  PersonalGrowth: "Kişisel Gelişim",
  NatureBios: "Doğa / Canlılar",
  CultureEducation: "Kültür / Eğitim",
  CreativeArtDesign: "Yaratıcı / Sanat / Tasarım",
  MusicLiteratureCinema: "Müzik / Edebiyat / Sinema",
  MagazineEvents: "Magazin / Etkinlik",
  WorldNews: "Dünya Haberleri",
  FoodaDrink: "Yeme / İçme",
  TravelExplore: "Seyahat / Keşfet",
  selectCover: "Kapak seç",
  pleaseWaitUntilAutomaticBablFinish:
    "Otomatik babl oluşturuluyor, lütfen oluşturulana kadar bekleyin.",
  automaticBablGenerated: "Otomatik babl oluşturuldu.",
  selectCoverFirst: "Lütfen önce kapak seçin",
  pleaseEnterBablTitle: "Lütfen ürün açıklaması girin",
  pleaseSelectBablCategory: "Lütfen Babl kategorisi seçin",
  pleaseEnterPrompt:
    "Lütfen istemi girin veya otomatik babl oluşturma seçeneğini kapatın.",
  title: "Başlık",
  enterBablTitle: "Ürün açıklaması girin",
  createAutoBabl: "Otomatik Babl oluştur",
  PoweredByAI: "AI ile güçlendirildi",
  enterDetailedPrompt: "Ayrıntılı bilgi istemini girin",
  SelectVideoOrPhotoToAddProduct: "Ürün eklemek için video veya fotoğraf seçin",
  areYouSureToCancelBabl: "Ürünü iptal etmek istediğinize emin misiniz?",
  videoAndShortVideo: "Videodan",
  Done: "Tamamlandı",
  Recharge: "Bakiye Yükle",
  CongratulationsAccount: "Tebrikler, coin hesabınıza eklendi.",
  AnUnexpectedLater:
    "Satın alma sırasında beklenmeyen bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
  BuyCoins: "Coin satın al",
  Filter: "Filtrele",
  Bookmarks: "Kitaplık",
  photo: "Fotoğraf",
  text: "Yazı",
  music: "Müzik/Podcast",
  stream: "Yayın",
  shop: "Alışveriş",
  shortVideo: "Kısa video",
  video: "Video Tanıtımlı Ürünler ",
  AddHeaderWithinBabl: "Babl`a Başlık Ekle",
  AddBackground: "Arka plan ekle",
  regenerate: "Yeniden oluştur",
  changeTemplate: "Şablon değiştir",
  edit: "Düzenle",
  finish: "Bitir",
  add: "Ekle",
  createNewBabl: "Alt Babl Oluştur",
  addExistingBabl: "Mevcut Babl`ı Ekle",
  bablPriceCantNegative: "Babl fiyatı negatif olamaz.",
  congratsBablShared: "Tebrikler, gönderin paylaşıldı",
  congratsSubBablAdded: "Tebrikler, alt babl eklendi",
  pleaseSelectAtLeastContent: "Lütfen en az 1 içerik ekleyin",
  enterHashtag: "#Hashtag ekle",
  interaction: "Etkileşim",
  allowOthersToAdd:
    "Başkalarının babl`ını istedikleri herhangi bir babl`a eklemesine izin ver",
  Info: "Bilgi",
  pleaseEnterValidPrice: "Lütfen geçerli bir fiyat girin",
  ChooseShortTopic: "Konunuz için kısa bir video kapağı seçin",
  YouCanTopic: "Konu hakkında buraya\nbir açıklama yazabilirsiniz",
  enterInfo: "Ön bilgi ekleyin",
  Price: "Fiyat",
  AddYourText: "Yazı ekle...",
  NewMessage: "Yeni Mesaj",
  createBabl: "Ürün Ekleyin",
  howtoday: "Size nasıl yardımcı olabilirim?",
  BABLAI: "BABL AI",
  AskAnything: "Soru sor",
  ThisByUser: "Bu Babl kullanıcı tarafından silindi",
  UpdateMyNewPassword: "Yeni Şifremi Güncelle",
  SendBablCoin: "Babl Coin Gönder",
  BablCategories: "Kategoriler",
  ConfirmEmail: "Eposta Adresinize Gelen Kodu Girin",
  ErrorGift:
    "Hediye gönderilirken beklenmeyen bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
  dontHaveEnoughCoins: "Yeterli paranız yok.",
  wouldYouLikeToBuyCoins: "Coin satın almak ister misiniz?",
  YouAreBuying: "Satın alıyorsunuz",
  Unfollow: "Çıkar",
  YouAreSending: "Gönderiyorsunuz",
  AreYourSure: "Emin misiniz?",
  Gift: "Hediye et",
  Buy: "Satın al",
  CongratulationsCoinSent: "Tebrikler, coin gönderildi.",
  YouCantYourself: "Kendinize para gönderemezsiniz.",
  PleaseEnterTheSend: "Lütfen göndermek istediğiniz tutarı giriniz",
  YouCanSendBablCongrats: "Tebriklere babl coin veya hediye gönderebilirsiniz",
  EnterCustomAmount: "Özel tutarı girin",
  YouYet: "Henüz paylaşılan içeriğiniz yok.",
  AreYouDelete: "Silmek istediğinizden emin misiniz?",
  myAccount: "Hesabım",
  yes: "Evet",
  YouCanSendGift: "Hediye gönderebilirsiniz",
  Temp1Desc:
    "Babl`lara odaklanır, aralarında boşluk yoktur ve gruplama için kaydırma fonksiyonu yoktur.",
  Temp2Desc:
    "Babl`lara odaklanır, aralarında boşluk yoktur ve gruplama için kaydırma fonksiyonu vardır.",
  Temp3Desc:
    "Babl`larınızda bir arka plan olabilir, aralarında daha fazla boşluk vardır  ve gruplama için kaydırma fonksiyonu yoktur.",
  Temp4Desc:
    "Babl`larınızda bir arka plan olabilir, aralarında daha fazla boşluk vardır  ve gruplama için kaydırma fonksiyonu vardır.",
  Temp5Desc:
    "Babl`ların yerleşimlerinin belirli kuralları yoktur, tasarım içerir ve kaydırma fonksiyonu isteğe bağlıdır.",
  Temp6Desc:
    "Çok miktarda içeriği düzenli bir şekilde görüntüleyebilirsiniz ve kaydırma fonksiyonu isteğe bağlıdır.",
  helpandfeedback: "Yardım Ve Geribildirim",
  helpdc: "Yardım ve destek kaynaklarına erişin ve sorunları çözün.",
  feedback: "Geri bildirim",
  help: "Yardım",
  pleasefeedback: "Lütfen geri bildirimini ekle",
  feedbackSent: "Geri bildiriminiz iletildi.",
  fq1: "Hangi tür içerikler Bablworld'de bulunabilir?",
  fqd1: "Bablworld, metin, görsel, video, kısa video, canlı yayin, ürün, müzik, podcast, her türlü internet sayfası, pdf ve diğer medya türlerini içeren geniş bir format yelpazesi sunar. Kullanıcılar, konularını en iyi şekilde anlatmak için farklı formatlari bir araya getirebilirler.",
  fq2: "Yapay zeka uygulamada nasıl kullanılır?",
  fqd2: "Uygulamadaki yapay zeka, kullanıcı davranışlarını analiz ederek kişiselleştirilmiş öneriler sunmak, içerikleri kullanıcıya göre optimize etmek ve uygulama deneyimini geliştirmek için çalışır. Babl oluştururken kullanıcılar, yapay zeka entegrasyonundan yararlanarak en iyi ve en doğru içerikleri seçebilir ve düzenleyebilirler. Bu, kullanıcıların daha etkili ve ilgi çekici Babl`lar oluşturmalarına yardımcı olur.",
  fq3: "Oturum Açma Problemlerini Nasıl Çözebilirim?",
  fqd3: '"Şifremi Unuttum" seçeneğini kullanarak yeni bir şifre oluşturabilirsiniz veya uygulama destek ekibiyle iletişime geçebilirsiniz.',
  fq4: "Uygulama Verilerimi Nasıl Kullanıyor?",
  fqd4: "Kişisel verileriniz gizliliğinizi korumak amacıyla yalnızca uygulama işlevselliği için kullanılır ve üçüncü taraflarla paylaşılmaz. Veriler şifrelenir ve güvenli sunucularda saklanır.",
  fq5: "Otomatik bablda en doğru sonuçları almam için ne yapmam gerekir?",
  fqd5: "Otomatik Babl oluşturma aşamasında bilgi kısmına ne kadar detaylı, spesifik ve çeşitli bilgi yazılırsa o kadar doğru sonuç verir. Kullanıcı aklındaki Babl`ı oluşturmak için yapay zekaya en net komutları ve anahtar kelimeleri vermelidir.",
  popup: "Tamam",
  PhoneNumber: "Telefon Numaranız",
  SignUpComplete: "Devam Et",
  settings: "Ayarlar",
  PazaarfyPremium: "Pazaarfy Premium",
  ProfileInformation: "Profil Bilgileri",
  ChangeLanguage: "Dil Değiştir",
  LiveSupport: "Canlı Destek",
  changePassword: "Şifre Değiştir",
  ChangePassword: "Şifre Değiştir",
  PrivacyAgreement: "Gizlilik Sözleşmesi",
  editInformation: "Bilgilerini Güncelle",
  selectCategory: "Kategori Seçin",
  MyStore: "Mağazam",
  AddProduct: "Ürün Ekle",
  writemessage: "Mesaj yazın",
  Pazar: "Pazar",
  SearchProduct: "Ürün arayın",
  Product: "Tüm Ürünler",
  PazaarfyAI: "Yapay Zeka İle Arama",
  NoMatchingProductFound: "Eşleşen ürün bulunamadı",
  PleaseSelectPhotoOrVideo: "Lütfen Kamaredan Veya Galeriden Görsel Seçin",
  Logout: "Çıkış Yap",
  Sends: "Gönderilerim",
  Likeda: "Beğendiklerim",
  Trend: "Trend Ürünler",
  BestSellers: "Çok Satanlar",
  Notifications: "Bildirimler",
  reply: "yanıt",
  SelectFromGallery: "Galeriden Seç",
  OpenCamera: "Kamera Aç",
  ForgotPasswordF: "Şifremi Unuttum",
  UsernameReq: "Kullanıcı adı zorunludur",
  EmailReq: "E-posta girmek zorunludur",
  il1: "🛍️ Moda & Aksesuar ",
  id1: "Giyim, ayakkabı, çanta ve takılar",
  il2: "📱 Teknoloji & Elektronik",
  id2: "Akıllı telefonlar, bilgisayarlar, kulaklıklar",
  il3: "🏠 Ev & Yaşam",
  id3: "Dekorasyon, mutfak eşyaları, mobilyalar",
  il4: "💄 Kozmetik & Kişisel Bakım",
  id4: "Makyaj, cilt bakımı, parfümler",
  il5: "🎮 Oyun & Eğlence",
  id5: "Konsollar, masa oyunları, figürler",
  il6: "🏋️‍♀️ Spor & Outdoor",
  id6: "Fitness ekipmanları, kamp malzemeleri",
  sl1: "🔥 Trend ve Popüler Ürünler",
  sl2: "🎥 Video İçerikli",
  sl3: "📸 Bol Görselli",
  sl4: "⏳ Kısa ve Öz Bilgili",
  sl5: "🛒 Kampanya ve İndirim Odaklı",
  sl6: "🌍 Global ve Yenilikçi Ürünler",
  MySituation: "Durumlar",
  SearchUser: "Kullanıcı arayın",
  Warnings: "Uyarı",
  PhotoWarning: "Lütfen en az bir fotoğraf seçin",
  PhotoFive: "En fazla 5 içerik yükleyebilirsiniz",
  TermsText: "Kullanım Şartları’nı okudum ve kabul ediyorum.",
  errorKVKK: "Kullanım şartlarını kabul etmelisiniz.",
  Back: "Geri dön",
  PreHome: "Öne Çıkan Ürünler",
  Stores: "Mağazalar",
  HideDescription:
    "Rahatsız Edici İçerik Bildiriminiz Alındı Bildiriminiz başarıyla alındı. İçerik ekibimiz gerekli kontrolleri sağlayacak ve 24 saat içerisinde içeriği kaldıracak veya ilgili kullanıcıya yazılı bir uyarı gönderecektir. İlginiz ve desteğiniz için teşekkür ederiz.",
  GetNotification: "Bildirim Alındı",
  GuestMode: "Misafir Modu",
  LeaveGuestMode: "Misafir Moddan Ayrıl",
  kv1: "Pazaarfy Kullanım Şartları",
  kv2: "Bu şartlar, Pazaarfy uygulamasını kullanırken uyulması gereken kuralları belirtir. Pazaarfy, kullanıcılar arasında güvenli, saygılı ve pozitif bir ortam oluşturmayı hedefler. Bu nedenle aşağıdaki davranışlara kesinlikle izin verilmez. Yasa dışı, şiddet içerikli, müstehcen, nefret söylemi barındıran veya taciz niteliğindeki içeriklerin paylaşılması, diğer kullanıcılara yönelik tehdit, hakaret, zorbalık veya her türlü rahatsız edici davranış. Uygulamanın işleyişine zarar verecek spam, dolandırıcılık ya da kötüye kullanım eylemlerine kesinlikle izin verilmez. Bu kurallara uymayan kullanıcıların hesapları 24 saat içerisinde kapatılır.",
  kv3: "1. Hizmet Tanımı",
  kv4: "Pazaarfy, kullanıcıların ürünleri görüntüleyebildiği, listeleyebildiği ve paylaşabildiği bir sosyal pazar uygulamasıdır.",
  kv5: "2. Kabul Edilen Kullanım",
  kv6: "Kullanıcılar, yasa dışı, saldırgan, tehdit edici, nefret söylemi içeren veya müstehcen içerikler paylaşamaz.",
  kv7: "3. İçerik Denetimi",
  kv8: "Uygunsuz içerikler kullanıcılar tarafından bildirilebilir ve 24 saat içinde moderatörler tarafından incelenir.",
  kv9: "4. Engelleme ve Raporlama",
  kv10: "Kullanıcılar diğer kullanıcıları engelleyebilir ve uygunsuz içerikleri raporlayabilir.",
  kv11: "5. Gizlilik",
  kv12: "Paylaşılan içerikler herkese açık olabilir. Özel bilgilerinizin gizliliğini sağlamak sizin sorumluluğunuzdadır.",
  kv13: "6. Sözleşmenin İhlali",
  kv14: "Kuralları ihlal eden kullanıcıların hesapları uyarılmadan kapatılabilir veya askıya alınabilir.",
  preview: "ÖNİZLEME",
};
