export default {
  sureToDeleteChat: "您确定要删除此对话吗？",
  longPressToSee: "长按查看",
  interactionRequestNotif: "互动请求",
  giftNotif: "礼物/硬币",
  areYouSureToAddItem: "您确定要将此帖子添加到收藏中吗？",
  itemAddedToCollection: "帖子已添加到收藏。",
  goOrigin: "您确定要访问原始内容吗？",
  follower: "关注者",
  following: "正在关注",
  languageSelection: "选择语言",
  continue: "继续",
  selectedCategory: "选择类别",
  OnBoardDescOne:
    "Pazaarfy 在这里让您的购物体验更有趣、更轻松。您可以销售自己的产品，也可以享受其他人提供的精彩优惠。现在开始探索吧！",
  Skip: "跳过",
  Hide: "令人反感的內容",
  OnBoardDescTwo:
    "在购物时，我们为您展示最适合的内容和优惠。浏览类别，轻松找到您想要的产品。我们在这里为您挑选最好的！",
  OnBoardThree:
    "在 Pazaarfy 购物，享受最新的优惠和折扣。进入充满促销的世界，立刻开始节省！",
  OnBoardFour:
    "在创建 Babl 时，选择关联平台的内容，选择一个引人注目的模板，并建议选择一个动态封面。",
  OnBoardFive:
    "使用子 Babl 功能，您可以在任何主题下创建子标题，并深入探讨该主题。",
  OnBoardSix: "在您感兴趣的主题下，您可以添加允许的格式内容，并鼓励互动。",
  Continue: "继续",
  Login: "登录",
  Email: "电子邮件",
  Search: "搜索",
  MyBabls: "我的 Babls",
  share: "分享",
  SelectBablFromHere: "从这里选择 Babl。",
  TapToGoToSiteForShareContentToSharedSavings:
    "点击前往网站，在分享库中分享内容",
  BablSearch: "Babl 搜索",
  Password: "密码",
  Forgot: "忘记密码了吗？",
  LoginGmail: "使用 Google 登录",
  LoginApple: "使用 Apple 登录",
  account: "账户",
  DontHaveAnAccount: "还没有账户？",
  DoHaveAnAccount: "已经有账户？",
  SignUp: "注册",
  Username: "用户名",
  PasswordAgain: "再次输入密码",
  WhatDoYouLike: "告诉我们您的主要购买目标，以便为您提供定制的解决方案",
  SelectYourInterests: "选择您的兴趣",
  createYourself: "创建",
  Which: "哪种",
  DoYouLikeTheContentStyle: "您喜欢这种内容风格吗？",
  ShortVideo: "短视频",
  Video: "视频介绍产品",
  Photo: "照片",
  Text: "文本",
  Music: "音乐/播客",
  LiveStream: "直播",
  Followss: "关注",
  Shop: "购物",
  Internet: "互联网",
  ForYou: "为您推荐",
  Following: "正在关注",
  FollowedBabls: "已关注的 Babls",
  Collections: "我的收藏",
  NewCollections: "新收藏",
  EnterCollectionName: "输入收藏名称",
  Cancel: "取消",
  Save: "保存",
  MakeItPublic: "公开",
  CollectionsDesc: "公开设置的收藏将在您的个人资料中显示，并可与朋友分享。",
  whatKindOfTopicYouThinking: "您在考虑什么主题？",
  ReanimatedSharedValue: "重新激活共享值",
  Saved: "已保存",
  Saveddd: "已保存",
  Savedd: "已保存",
  ShareLibrary: "分享库",
  AutomaticBablCreation: "自动创建 Babl",
  Loading: "加载中 %",
  PrivacyPolicy: "隐私政策",
  notifications: "通知",
  TermsOfUse: "使用条款",
  About: "关于",
  AppNotifications: "应用通知设置",
  Likes: "喜欢",
  Rebabls: "Rebabls",
  Sends: "发送",
  Comments: "评论",
  changePasswordDesc: "输入您的电子邮件地址以更改密码",
  Followers: "关注者",
  FollowersL: "关注者",
  Messages: "消息",
  Live: "实时",
  NewPost: "新帖子",
  ThereIsARegisteredEaddress: "此用户名或电子邮件地址已注册。",
  YourPasswordHasBeenReset: "您的密码已重置",
  VerificationCodeNotFound: "未找到验证码",
  VerificationCodeIsIncorrect: "验证码不正确",
  AnErrorPassword: "重置密码时发生错误。",
  EnterYourNewPassword: "请输入您的新密码",
  VerificationCode: "验证码",
  YourNewPassword: "您的新密码",
  YourNewPasswordAgain: "再次输入您的新密码",
  PasswordRepeat: "密码与重复密码不匹配。",
  CreateMyNewPassword: "创建我的新密码",
  GetCode: "发送验证码",
  AnErrorOccurredWhileSendingTheVerificationCode: "发送验证码时发生错误。",
  SendVerificationCode: "发送验证码",
  CanAddress: "请提供您的电子邮件地址",
  CONGRATULATIONS: "恭喜！",
  YourNewPasswordSuccessfully: "您的新密码已成功创建。",
  ThereIsAddress: "此用户名或电子邮件地址已注册。",
  YourPasswordLong: "您的密码必须至少包含 8 个字符。",
  AnUnexpectedErrorOccurred: "发生了意外错误。",
  AnErrorLogging: "登录时发生错误。",
  ItMustBeTheSameRepeat: "密码重复输入必须一致。",
  Sport: "运动",
  Health: "健康",
  Economy: "配件",
  Beauty: "美丽",
  Shopping: "购物",
  Technology: "技术",
  Trip: "旅行",
  Politics: "政治",
  FoodDrink: "食品和饮料",
  Entertainment: "娱乐",
  Current: "潮流",
  Magazine: "杂志",
  Activities: "活动",
  Fashion: "时尚",
  Culture: "文化",
  Education: "教育",
  Art: "艺术",
  Design: "设计",
  Nature: "自然",
  Work: "工作",
  Motivation: "动力",
  SelfImprovement: "自我提升",
  Psychology: "心理学",
  Science: "科学",
  Universe: "宇宙",
  ThisOwner: "此 Babl 已被所有者锁定。",
  WantToUnlockCoinsWrong: "您想用硬币解锁它吗？",
  Yes: "是的",
  AreYouBabl: "您确定要解锁此 Babl 吗？",
  BablSaved: "帖子已保存",
  BookmarkHasBeenDeleted: "书签已删除。",
  UserBlocked: "用户已被阻止",
  BablHasBeenDeleted: "帖子已删除。",
  AddCollections: "添加到收藏",
  GoToProfile: "前往个人资料",
  NotInterested: "不感兴趣",
  MarkedAsNotInterested: "已标记为不感兴趣。",
  Report: "举报",
  Hide: "隐藏",
  BlockUser: "屏蔽用户",
  AreYouUser: "您确定要屏蔽此用户吗？",
  areYouSure: "您确定吗？",
  areYouSureToAcceptInteraction: "您确定要接受将内容添加到 Babl 中的请求吗？",
  GetOutRebabs: "退出我的 Rebabs",
  Delete: "删除",
  youAreDeletingBabl: "您正在删除此帖子。",
  requestSent: "请求已发送。",
  requestAccepted: "请求已接受。",
  requestDenied: "请求已拒绝。",
  Edit: "编辑",
  rebabledby: "由...Rebabll",
  PleaseSelectContent: "请选择至少一项内容",
  YouWillSendARequestToAddContentAreYouSure:
    "您将发送请求以添加内容。您确定吗？",
  Follow: "关注",
  Followingg: "正在关注",
  SexualContent: "性内容",
  ViolentOrRepulsiveContent: "暴力或令人反感的内容",
  HatefulOrAbusiveContent: "仇恨或侮辱性内容",
  HarassmentOrBullying: "骚扰或欺凌",
  HarmfulOrDangerousActs: "有害或危险行为",
  Misinformation: "错误信息",
  ChildAbuse: "儿童虐待",
  LegalIssue: "法律问题",
  PromotesTerrorism: "鼓吹恐怖主义",
  SpamOrMisleading: "垃圾信息或误导性内容",
  Other: "其他",
  YourReportSent: "您的举报已发送",
  PleaseSelectOption: "请选择一个选项",
  CollectionDeleted: "收藏已删除",
  Public: "公开",
  Private: "私密",
  AreYouSureCollection: "您确定要删除此收藏吗？",
  no: "否",
  Send: "发送",
  SendYourComplaint: "发送您的投诉",
  PleaseEnterYourMessage: "请输入您的消息",
  AIGENERATEDTEXT: "AI 生成的文本",
  BablFollowers: "Babl 追随者",
  ManageBabls: "管理 Babls",
  Shared: "已分享",
  CongratulationsSsuccessfully: "恭喜，已成功添加。",
  AddToShareLibrary: "添加到分享库",
  CongratulationsItHasBeenAddedSuccessfully: "恭喜，已成功添加",
  OK: "确定",
  Answers: "回答",
  AddComment: "添加评论...",
  wouldYouLikeToDeleteYourComment: "您确定要删除您的评论吗？",
  YourCommentHasBeenDeleted: "您的评论已删除。",
  PleaseCheckYourInternetConnection: "请检查您的互联网连接",
  requestsIGet: "收到的请求",
  requestsISent: "我发送的请求",
  controlPanel: "控制面板",
  close: "关闭",
  Close: "关闭",
  bablSettings: "Babl 设置",
  CollectionBabls: "收藏 Babl",
  AddedTo: "已添加到",
  SelectTextFromHere: "从这里选择文本",
  SelectFromHere: "从这里选择",
  SelectStreamFromHere: "从这里选择流",
  SelectShortFromHere: "从这里选择短视频",
  SelectProductFromHere: "从这里选择产品",
  SelectMusic: "选择音乐",
  all: "电子产品",
  SelectVideoFromHere: "从这里选择视频",
  noGalleryAccess: "没有访问画廊的权限。",
  wouldYouLikeToGoSettins: "您想去设置中授予访问权限吗？",
  TapScreenToEnter: "点击屏幕进入",
  Rebabled: "已重新启用",
  WouldYouLikeToGoOriginalContent: "您想转到原始内容吗？",
  Daily: "每日",
  Weekly: "每周",
  Monthly: "每月",
  HotBabls: "热门 Babl",
  ShareTo: "分享至",
  CopyLink: "复制链接",
  BablSent: "Babl 已发送",
  WriteAMessage: "写消息..",
  BablLinkCopied: "Babl 链接已复制",
  AnErrorOccurredLater: "删除数据时发生错误，请稍后再试。",
  userDetails: "用户详情",
  password: "密码",
  language: "语言",
  deleteMyAccount: "删除我的账户",
  sureToDeleteAccount: "您确定要删除账户吗？",
  Transactions: "交易",
  Deposit: "存款",
  Withdraw: "提现",
  Gifts: "礼物",
  MyGifts: "我的礼物",
  TotalAssets: "总资产",
  SearchTransaction: "搜索交易",
  Payment: "支付",
  Congratulations: "恭喜",
  Verification: "验证",
  ConfirmTheCodeReceivedInYourEmail: "确认您收到的电子邮件中的代码",
  Confirm: "确认",
  DeleteCollection: "删除收藏",
  AreYouSureYouWantToDeleteTheCollection: "您确定要删除这个收藏吗？",
  Sorry: "抱歉 :(",
  YourAccountHasBeenSuccessfullyDeleted: "您的账户已成功删除",
  CreateNewAccount: "创建新账户",
  AreYouSureToBlockUser: "您确定要封锁该用户吗？",
  AnErrorOccured: "发生了一个错误。",
  AreYouSureToReportUser: "您确定要举报该用户吗？",
  ReportUser: "举报用户",
  Success: "成功",
  WouldYouLikeToRemovePin: "您想移除此图钉吗？",
  WouldYouLikeToPinThisBabl: "您想钉住这个 Babl 吗？",
  ManageContentsBabls: "管理将添加到您的 Babl 中的内容。",
  ManageYourAccountUpdateYourprofileInformationAndConfigureYourPreferences:
    "管理您的账户，更新个人资料信息并配置偏好设置。",
  BalanceAndMonetary: "余额与财务",
  CheckYourTransactions:
    "检查您的余额状况，查看支付历史记录并管理您的财务交易。",
  AdjustImportantEvents: "调整通知设置，获取更新并及时了解重要事件。",
  about: "关于",
  AreYouSureToDelete: "您确定要删除吗？",
  LearnDevelopers: "了解更多应用信息，检查版本号并与开发者联系。",
  sureToLogout: "您确定要退出登录吗？",
  profileSettings: "个人资料设置",
  exit: "退出",
  VerificationSystem: "验证系统",
  Contents: "内容",
  People: "用户",
  Hashtag: "标签",
  CreBabl: "创建 Babl..",
  YouDontYet: "您还没有关注的内容。",
  Yesterday: "昨天",
  Today: "今天",
  Notifications: "通知",
  ProfileInformationUpdated: "个人资料信息已更新",
  ProfileSettings: "个人资料设置",
  AccessPermissionGranted: "没有访问画廊的权限。",
  DoYouWantAccess: "您想去设置中授予访问权限吗？",
  PersonalInformation: "个人信息",
  name: "商店名称",
  SocialMediaLink: "社交媒体链接",
  BablFocusedNoSlide: "Babl 集中（无滑块）",
  BablFocusedSlider: "Babl 集中（带滑块）",
  BackgroundFocusedNoSlider: "背景集中（无滑块）",
  BackgroundFocusedWithSlider: "背景集中（带滑块）",
  ModernDesign: "现代设计",
  EasyToConsume: "易于使用",
  pleaseSelectTemplate: "请选择模板",
  templateSelection: "模板",
  WithDraw: "提现",
  AmountOfMoney: "金额",
  Convert: "转换",
  ConvertibleGift: "可转换礼物",
  Amount: "金额",
  ConvertibleCoin: "可转换硬币",
  ConvertToBablCoin: "转换为 Babl Coin",
  Pull: "提现",
  YouDoNotHaveEnoughFunds: "您没有足够的资金。",
  PleaseCorrectly: "请确保您的 IBAN 号码正确。",
  ThereIsNoGiftInYourAccount: "您的账户中没有礼物",
  YouBuy: "您的账户中没有足够的硬币。您想购买吗？",
  YourCreated: "您的提现请求已创建。",
  WithdrawalProcess: "提现过程",
  ThisMonth: "本月",
  Tulip: "郁金香",
  GoldBall: "金球",
  Coconut: "椰子",
  Coffee: "咖啡",
  Heart: "心形",
  JavaCoffee: "爪哇咖啡",
  Cat: "猫",
  Dog: "狗",
  SoyBeans: "大豆",
  Badge: "徽章",
  Peanut: "花生",
  Lipstick: "口红",
  TraditionalGong: "传统锣",
  Bison: "野牛",
  Mask: "面具",
  WayangSymbols: "瓦扬符号",
  Wand: "魔杖",
  BakpiaPathong: "巴克皮亚巴通",
  JamGodang: "詹姆·戈丹",
  Wayang: "瓦扬",
  GameConsol: "游戏主机",
  DeepSearch: "深度搜索",
  OliveBranch: "橄榄枝",
  GoldPen: "金笔",
  RambutanFruit: "红毛丹果",
  GoldMedal: "金牌",
  Flower: "花",
  TraditionalWoodcraft: "传统木工",
  GoldenCup: "金杯",
  Astreoid: "小行星",
  MagicSphere: "魔法球",
  Ring: "戒指",
  Diamond: "钻石",
  MentalHealth: "心理健康",
  PersonalGrowth: "个人成长",
  NatureBios: "自然/生物",
  CultureEducation: "文化/教育",
  CreativeArtDesign: "创意/艺术/设计",
  MusicLiteratureCinema: "音乐/文学/电影",
  MagazineEvents: "杂志/活动",
  WorldNews: "世界新闻",
  FoodaDrink: "美食/饮品",
  TravelExplore: "旅行/探索",
  selectCover: "选择封面",
  pleaseWaitUntilAutomaticBablFinish: "自动 Babl 正在生成，请稍等。",
  automaticBablGenerated: "自动 Babl 已生成。",
  selectCoverFirst: "请先选择封面",
  pleaseEnterBablTitle: "请输入产品描述",
  pleaseSelectBablCategory: "请选择 Babl 类别",
  pleaseEnterPrompt: "请输入提示或关闭自动 Babl 创建选项。",
  title: "标题",
  enterBablTitle: "输入产品描述",
  createAutoBabl: "创建自动 Babl",
  PoweredByAI: "由 AI 提供支持",
  enterDetailedPrompt: "输入详细的提示信息",
  SelectVideoOrPhotoToAddProduct: "选择视频或照片以添加产品",
  areYouSureToCancelBabl: "您确定要取消此产品吗？",
  videoAndShortVideo: "视频 & 短视频",

  Done: "完成",
  Recharge: "充值",
  CongratulationsAccount: "恭喜，硬币已添加到您的账户。",
  AnUnexpectedLater: "购买过程中发生了意外错误，请稍后再试。",
  BuyCoins: "购买硬币",
  Filter: "筛选",
  Bookmarks: "书签",
  photo: "照片",
  text: "文字",
  music: "音乐/播客",
  stream: "流",
  shop: "购物",
  shortVideo: "短视频",
  video: "视频推广产品",
  AddHeaderWithinBabl: "在 Babl 中添加标题",
  AddBackground: "添加背景",
  regenerate: "重新生成",
  changeTemplate: "更改模板",
  edit: "编辑",
  finish: "完成",
  add: "添加",
  createNewBabl: "创建新 Babl",
  addExistingBabl: "添加现有 Babl",
  bablPriceCantNegative: "Babl 价格不能为负。",
  congratsBablShared: "恭喜，您的发布已分享",
  congratsSubBablAdded: "恭喜，子 Babl 已添加",
  pleaseSelectAtLeastContent: "请至少添加一个内容",
  enterHashtag: "添加 #标签",
  interaction: "互动",
  allowOthersToAdd: "允许其他人将其 Babl 添加到任何他们想要的 Babl 中",
  Info: "信息",
  pleaseEnterValidPrice: "请输入有效的价格",
  ChooseShortTopic: "为您的主题选择短视频封面",
  YouCanTopic: "您可以在此写下\n关于主题的说明",
  enterInfo: "添加预信息",
  Price: "价格",
  AddYourText: "添加文字...",
  NewMessage: "新消息",
  createBabl: "添加产品",
  howtoday: "我能为您做些什么？",
  BABLAI: "BABL AI",
  AskAnything: "问任何问题",
  ThisByUser: "此 Babl 已由用户删除",
  UpdateMyNewPassword: "更新我的新密码",
  SendBablCoin: "发送 Babl Coin",
  BablCategories: "类别",
  ConfirmEmail: "输入您邮箱收到的代码",
  ErrorGift: "发送礼物时发生了意外错误，请稍后再试。",
  dontHaveEnoughCoins: "您没有足够的硬币。",
  wouldYouLikeToBuyCoins: "您想购买硬币吗？",
  YouAreBuying: "您正在购买",
  Unfollow: "取消关注",
  YouAreSending: "您正在发送",
  AreYourSure: "您确定吗？",
  Gift: "赠送",
  Buy: "购买",
  CongratulationsCoinSent: "恭喜，硬币已发送。",
  YouCantYourself: "您不能向自己发送资金。",
  PleaseEnterTheSend: "请输入您要发送的金额",
  YouCanSendBablCongrats: "恭喜，您可以发送 Babl coin 或礼物",
  EnterCustomAmount: "输入自定义金额",
  YouYet: "您尚未共享任何内容。",
  AreYouDelete: "您确定要删除吗？",
  myAccount: "我的账户",
  yes: "是的",
  YouCanSendGift: "您可以发送礼物",
  Temp1Desc: "专注于 Babl，没有间隙，并且没有滑动功能进行分组。",
  Temp2Desc: "专注于 Babl，没有间隙，并且有滑动功能进行分组。",
  Temp3Desc: "您的 Babl 可以有背景，间隙更大，并且没有滑动功能进行分组。",
  Temp4Desc: "您的 Babl 可以有背景，间隙更大，并且有滑动功能进行分组。",
  Temp5Desc: "Babl 的布局没有特定规则，包含设计，并且滑动功能是可选的。",
  Temp6Desc: "可以以有序的方式显示大量内容，滑动功能是可选的。",
  helpandfeedback: "帮助与反馈",
  helpdc: "访问帮助和支持资源，解决问题。",
  feedback: "反馈",
  help: "帮助",
  pleasefeedback: "请提供您的反馈",
  feedbackSent: "您的反馈已提交。",
  fq1: "Bablworld 中可以找到哪些类型的内容？",
  fqd1: "Bablworld 提供了丰富的格式选项，包括文本、图像、视频、短视频、直播、产品、音乐、播客、所有类型的网页、PDF 等。用户可以结合不同的格式来最好的展示他们的主题。",
  fq2: "应用中的人工智能是如何工作的？",
  fqd2: "应用中的人工智能通过分析用户行为，提供个性化推荐、优化内容并改善应用体验。在创建 Babl 时，用户可以利用人工智能集成来选择和编辑最佳内容，帮助他们创建更有效和吸引人的 Babl。",
  fq3: "如何解决登录问题？",
  fqd3: "您可以通过使用“忘记密码”选项来创建新密码，或者联系应用的支持团队。",
  fq4: "应用如何使用我的数据？",
  fqd4: "为了保护您的隐私，您的个人数据仅用于应用功能，并且不会与第三方共享。数据会被加密并存储在安全的服务器上。",
  fq5: "如何在自动 Babl 中获得最佳结果？",
  fqd5: "在创建自动 Babl 时，信息部分越详细、具体和多样化，结果就越准确。用户应给人工智能提供最明确的指令和关键词来创建他们想要的 Babl。",
  popup: "确定",
  PhoneNumber: "您的电话号码",
  SignUpComplete: "继续",
  settings: "设置",
  PazaarfyPremium: "Pazaarfy 高级版",
  ProfileInformation: "个人资料信息",
  ChangeLanguage: "更改语言",
  LiveSupport: "在线支持",
  changePassword: "更改密码",
  ChangePassword: "更改密码",
  PrivacyAgreement: "隐私协议",
  editInformation: "更新信息",
  selectCategory: "选择类别",
  MyStore: "我的商店",
  AddProduct: "添加产品",
  writemessage: "写信息",
  Pazar: "市场",
  SearchProduct: "搜索产品",
  Product: "所有产品",
  PazaarfyAI: "人工智能搜索",
  NoMatchingProductFound: "未找到匹配的产品",
  PleaseSelectPhotoOrVideo: "	请选择视频或图片",
  Logout: "退出",
  Sends: "我的发布",
  Likeda: "喜欢的",
  Trend: "流行产品",
  BestSellers: "畅销产品",
  Notifications: "通知",
  reply: "回复",
  SelectFromGallery: "从图库选择",
  OpenCamera: "打开相机",
  ForgotPasswordF: "忘记密码",
  UsernameReq: "用户名是必填的",
  EmailReq: "电子邮件是必填的",
  il1: "🛍️ 时尚与配饰",
  id1: "衣服、鞋子、包包和饰品",
  il2: "📱 科技与电子",
  id2: "智能手机、电脑、耳机",
  il3: "🏠 家居与生活",
  id3: "装饰、厨房用品、家具",
  il4: "💄 化妆与个人护理",
  id4: "化妆品、护肤、香水",
  il5: "🎮 游戏与娱乐",
  id5: "游戏主机、桌面游戏、手办",
  il6: "🏋️‍♀️ 体育与户外",
  id6: "健身设备、露营装备",
  sl1: "🔥 流行和热门产品",
  sl2: "🎥 视频内容",
  sl3: "📸 多图展示",
  sl4: "⏳ 简洁明了",
  sl5: "🛒 促销和折扣焦点",
  sl6: "🌍 全球和创新产品",
  MySituation: "我的情况",
  SearchUser: "搜索用户",
  Warnings: "警告",
  PhotoWarning: "請至少選擇一張照片",
  PhotoFive: "您最多可以上傳 5 則內容",
  TermsText: "我已閱讀並接受使用條款。",
  errorKVKK: "您必須接受使用條款",
  Back: "回去",
  PreHome: "特色產品",
  Stores: "商店",
  HideDescription:
    "您的攻擊性內容報告已收到 您的報告已成功收到。我們的內容團隊將進行必要的檢查，並在 24 小時內刪除該內容或向相關用戶發送書面警告。感謝您的關注與支持。",
  GetNotification: "收到通知",
  GuestMode: "訪客模式",
  LeaveGuestMode: "離開訪客模式",
  kv1: "Pazaarfy 使用条款",
  kv2: "本条款规定了在使用 Pazaarfy 应用时必须遵守的规则。Pazaarfy 致力于为用户营造一个安全、尊重和积极的环境。因此，严禁以下行为：发布非法、暴力、淫秽、仇恨或骚扰性质的内容；对其他用户进行威胁、侮辱、欺凌或任何形式的骚扰行为；以及任何破坏应用正常运行的行为，例如垃圾信息、欺诈或滥用。违反这些规则的账户将在 24 小时内被关闭。",
  kv3: "1. 服务描述",
  kv4: "Pazaarfy 是一个社交市场应用，用户可以浏览、发布和分享商品。",
  kv5: "2. 可接受的使用方式",
  kv6: "用户不得分享违法、攻击性、威胁性、仇恨言论或淫秽内容。",
  kv7: "3. 内容审核",
  kv8: "用户可以举报不当内容，管理员将在24小时内进行审核。",
  kv9: "4. 屏蔽与举报",
  kv10: "用户可以屏蔽其他用户并举报不当内容。",
  kv11: "5. 隐私",
  kv12: "分享的内容可能是公开的。保护您的个人隐私信息是您的责任。",
  kv13: "6. 违反协议",
  kv14: "违反规则的用户账户可能会被暂停或在无警告的情况下被终止。",
  preview: "預覽",
  InfoMarket: "店铺信息",
  ShareProfile: "Поделиться профилем",
  ShareLink: "在 Pazaarfy 应用上查找您的商店",
  LikedStore: "搜尋商店",
  SearchStore: "搜索商店",
  ShareStatus: "作为状态分享",
  GenerateQR: "產生二維碼",
  ForYou: "為你",
  Address: "地址",
};
