export const getGiftsData = (t) => {
  return [
    {
      image: require('../assets/lal.png'),
      text: t('Tulip'),
      type: 'TULIP',
      number: '2',
    },
    {
      image: require('../assets/ball.png'),
      text: t('GoldBall'),
      type: 'GOLD_BALL',
      number: '2',
    },
    {
      image: require('../assets/coco.png'),
      text: t('Coconut'),
      type: 'COCONUT',
      number: '2',
    },
    {
      image: require('../assets/coff.png'),
      text: t('Coffee'),
      type: 'COFFEE',
      number: '2',
    },
    {
      image: require('../assets/hear.png'),
      text: t('Heart'),
      type: 'HEART',
      number: '2',
    },
    {
      image: require('../assets/java_coffe.png'),
      text: t('JavaCoffee'),
      type: 'JAVA_COFFEE',
      number: '4',
    },
    {
      image: require('../assets/cat.png'),
      text: t('Cat'),
      type: 'CAT',
      number: '4',
    },
    {
      image: require('../assets/dog.png'),
      text: t('Dog'),
      type: 'DOG',
      number: '4',
    },
    {
      image: require('../assets/soy.png'),
      text: t('SoyBeans'),
      type: 'SOY_BEANS',
      number: '4',
    },
    {
      image: require('../assets/badg.png'),
      text: t('Badge'),
      type: 'BADGE',
      number: '8',
    },
    {
      image: require('../assets/peanut.png'),
      text: t('Peanut'),
      type: 'PEANUT',
      number: '8',
    },
    {
      image: require('../assets/ruj.png'),
      text: t('Lipstick'),
      type: 'LIPSTICK',
      number: '8',
    },
    {
      image: require('../assets/gong.png'),
      text: t('TraditionalGong'),
      type: 'TRADITIONAL_GONG',
      number: '8',
    },
    {
      image: require('../assets/bison.png'),
      text: t('Bison'),
      type: 'BISON',
      number: '20',
    },
    {
      image: require('../assets/maskk.png'),
      text: t('Mask'),
      type: 'MASK',
      number: '20',
    },
    {
      image: require('../assets/wayang.png'),
      text: t('WayangSymbols'),
      type: 'WAYANG_SYMBOLS',
      number: '20',
    },
    {
      image: require('../assets/as.png'),
      text: t('Wand'),
      type: 'WAND',
      number: '32',
    },
    {
      image: require('../assets/bakpi.png'),
      text: t('BakpiaPathong'),
      type: 'BAKPIA_PATHONG',
      number: '32',
    },
    {
      image: require('../assets/jam.png'),
      text: t('JamGodang'),
      type: 'JAM_GODANG',
      number: '32',
    },
    {
      image: require('../assets/wayangg.png'),
      text: t('Wayang'),
      type: 'WAYANG',
      number: '56',
    },
    {
      image: require('../assets/plain.png'),
      text: t('GameConsol'),
      type: 'YOU_ARE_PLAYING',
      number: '56',
    },
    {
      image: require('../assets/deep.png'),
      text: t('DeepSearch'),
      type: 'DEEP_SEARCH',
      number: '56',
    },
    {
      image: require('../assets/olive.png'),
      text: t('OliveBranch'),
      type: 'OLIVE_BRANCH',
      number: '56',
    },
    {
      image: require('../assets/goldpen.png'),
      text: t('GoldPen'),
      type: 'GOLD_PEN',
      number: '80',
    },
    {
      image: require('../assets/rambu.png'),
      text: t('RambutanFruit'),
      type: 'RAMBUTAN_FRUIT',
      number: '80',
    },
    {
      image: require('../assets/mad.png'),
      text: t('GoldMedal'),
      type: 'GOLD_MEDAL',
      number: '120',
    },
    {
      image: require('../assets/flower.png'),
      text: t('Flower'),
      type: 'FLOWER',
      number: '120',
    },
    {
      image: require('../assets/trad.png'),
      text: t('TraditionalWoodcraft'),
      type: 'TRADITIONAL_WOODCRAFT',
      number: '200',
    },
    {
      image: require('../assets/cup.png'),
      text: t('GoldenCup'),
      type: 'CUP',
      number: '300',
    },
    {
      image: require('../assets/Astreoid.png'),
      text: t('Astreoid'),
      type: 'ASTEROID',
      number: '300',
    },
    {
      image: require('../assets/magic.png'),
      text: t('MagicSphere'),
      type: 'MAGIC_SPHERE',
      number: '400',
    },
    {
      image: require('../assets/ring.png'),
      text: t('Ring'),
      type: 'RING',
      number: '400',
    },
    {
      image: require('../assets/diam.png'),
      text: t('Diamond'),
      type: 'DIAMOND',
      number: '600',
    },
  ];
};
